
format = """
[â•­â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â‰½â  ](bold  red)$username$hostname$directory$fill$time$fill$shell            
[â”£â”€â”€â”€â”€â”€â”€â”€â‰½â  ](bold white)$status$git_branch$git_status$git_commit$fill    $cmd_duration$fill
[â•°â”€â”€â‰½â  ](bold blue) $caracter
"""
[username]
style_user = "#890CA7 italic bold"
style_root = "#890CA7 italic bold"
format = "[$user]($style) "
disabled = false
show_always = true

[hostname]
ssh_only = false
format = '[on](white bold) [ğŸ‰ ](bg:black italic) [in](yellow italic bold) '
trim_at = "."
disabled = false
# â–‘â–‘â–‘â–‘â–‘â–‘
[fill]
symbol = 'â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘' 
style = ' black'

# Replace the "â¯" symbol in the prompt with "âœ"
[character]
success_symbol = '[â‰–â‰–â‰–> ](bold #4D0F28)[â‰–â‰–â‰–>> ](bold #7B00FF)[â‰–â‰–â‰–>>> ](bold #A2FF00)'
error_symbol = '[â‰–â‰–â‰–> ](bold #4D0F28)[â‰–â‰–â‰–>> ](bold #7B00FF)[â‰–â‰–â‰–>>> ](bold #A2FF00)'

# configure directory
[directory]
read_only = 'ğŸ”’'
truncation_length = 9
truncate_to_repo = false # truncates directory to root folder if in github repo
style = "bg:#black bold italic #E4953C underline"

# â™› ğŸµ  ğŸ¶   ğŸ“¸   ğŸ—‚    ğŸ“½     â¬  ğŸ“œ ğŸ©
[directory.substitutions]
"Documents" = " ğŸ—‚  "
"Downloads" = " â¬"
"Music" = " ğŸ¶"
"Pictures" = " ğŸ“¸ "
"BlackHat" = " ğŸ© "
"LearnLinux" = " ğŸ“œ "
"CyberSecurityToolKit" = " ğŸ”° "
# #890CA7
[time]
time_format = "%r"
format = " [$time](italic bright-purple)"
style = "bold"
use_12hr = true
disabled = false

[cmd_duration]
format = '[$duration]($style) '
min_time = 80
show_milliseconds = false
disabled = false
style = " italic #A2FF00"

[aws]
symbol = "â“ â“Œ â“ˆ "

[conda]
symbol = "ï„Œ "

[dart]
symbol = ""


[docker_context]
symbol = "Î”Î¦Ï‚ÎºÎÏ€"
format = "via [$symbol$context]($style) "
style = "blue bold"
only_with_files = true
detect_files = ["docker-compose.yml", "docker-compose.yaml", "Dockerfile"]
detect_folders = []
disabled = false

[elixir]
symbol = "î‰µ "

[elm]
symbol = ""

#ğŸŒ±
[git_branch]
truncation_length = 4
truncation_symbol = 'â€¦'
ignore_branches = ['']
symbol = 'ğŸŒ±'

[git_commit]
commit_hash_length = 4
tag_symbol = 'ğŸ”– '

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = '[ğŸ’ PICKING](bold red)'


[git_metrics]
added_style = 'bold blue'
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '
# ğŸ”°  âœ“  ğŸğŸ’¨  â­  ğŸŒ  ğŸŒ  âœ¦  à®ƒ  ğŸ…º   ğŸ’”  â›µ  ğŸŒ™  ğŸŒ•  âœ‰ï¸   ğŸ‘‘  ğŸ£   ğŸ¤–  ğŸª–  ğŸ‰  ğŸ§±  ğŸ”´  ğŸŸ¢  ğŸ”¥ğŸ’¯   â™¦ï¸   ğŸ¯
[git_status]
conflicted = 'âš ï¸ '
ahead = 'ğŸğŸ’¨â†¬  '
behind = 'â†« ğŸ˜°'
diverged = 'ğŸ˜µ'
up_to_date = 'ğŸŸ¢'
untracked = 'ğŸ¤·'
stashed = 'ğŸ“¦'
modified = 'ğŸ“'
staged = '[++\($count\)](green)'
renamed = 'âœï¸ '
deleted = 'ğŸ—‘ '

[golang]
symbol = "â’¼ â“„ "

[guix_shell]
disabled = true
format = "via (yellow bold) "
symbol = 'B '

[status]
style = 'bold red'
symbol = ' âŒ '
success_symbol = '  ğŸ’¯  '
not_executable_symbol = ' â›” '
not_found_symbol =  ' ğŸ” ' 
signal_symbol = 'âš¡'
pipestatus = true
pipestatus_separator = '|'
pipestatus_format = '\[$pipestatus\] => [$symbol$common_meaning$signal_name$maybe_int]($style)'
recognize_signal_code = true
format = '[\[$symbol$common_meaning$signal_name$maybe_int\]]($style) '
map_symbol = true
disabled = false


[hg_branch]
symbol = "ï˜ "

[java]
symbol = "â“™ â“ â“¥ â“ "

[julia]
symbol = ""

[memory_usage]
symbol = " ğŸ’¾ "

[nim]
symbol = " ïš¤ "
#7C22DC
[shell]
bash_indicator = ' Î²asÍŠh '
zsh_indicator = ' ZÍ sÍŠh  '
format = '[via](italic yellow)[$indicator]($style)'
style = 'bright-red'
disabled = false

[package]
symbol = " ğŸ“¦ "

[perl]
symbol = " âšª"

[php]
symbol = "â“… â“— â“Ÿ"

[python]
symbol = "â‚±Â¥"
pyenv_version_name = false
format = 'via [${symbol} (${version} )(\($virtualenv\) )]($style)'
style = "bold yellow"
pyenv_prefix = "venv "
python_binary = ["./venv/bin/python", "python", "python3", "python2"]
detect_extensions = ["py"]
version_format = "v${raw}"

[ruby]
symbol = "â“‡ â“¤ â“‘ â“¨"

[rust]
symbol = "â“‡ â“¤ â“¢ â“£"

[scala]
symbol = ""

[shlvl]
disabled = false
format = '[$symbol$shlvl]($style)'
repeat = true
symbol = 'â¯_'
repeat_offset = 1
threshold = 0

[swift]
symbol = "ï¯£ "

[nodejs]
format = "via [â“ƒ â“ â““ â“”  â’¿ â“ˆ  $version](bold green) "
detect_files = ["package.json", ".node-version"]
detect_folders = ["node_modules"]

